domain-needed
bogus-priv
no-resolv
no-poll
server=10.1.0.1
listen-address=192.168.254.1
cache-size=10000
no-hosts
bind-dynamic

## DHCP
no-dhcp-interface=eth1
log-dhcp
domain=lab.eviladmin.org
dhcp-option=3,192.168.254.1	# Router
dhcp-option=6,192.168.254.1	# DNS
dhcp-leasefile=/var/lib/misc/dnsmasq.leases
dhcp-range=192.168.254.50,192.168.254.60,12h

# hosts
dhcp-host=48:4d:7e:da:53:a5,192.168.254.101,node1
dhcp-host=34:17:eb:e1:da:a3,192.168.254.102,node2
dhcp-host=34:17:eb:e0:89:fb,192.168.254.103,node3

## tftp
enable-tftp
tftp-root=/data/tftp

# netboot
dhcp-boot=pxelinux.0
dhcp-match=set:efi-x86_64,option:client-arch,7
dhcp-boot=tag:efi-x86_64,grubx64.efi
