---
- name: Install dnsmasq and dnsutils
  become: true
  ansible.builtin.package:
    name:
      - dnsmasq
      - dnsutils
    state: present

- name: Enable/Start service dnsmasq
  become: true
  ansible.builtin.service:
    name: dnsmasq
    state: started
    enabled: yes

- name: Copy Config /etc/dnsmasq.d/dns.conf
  become: true
  ansible.builtin.copy:
    src: dns.conf
    dest: /etc/dnsmasq.d/dns.conf
    owner: root
    group: root
    mode: '0644' 
  notify:
    - Restart dnsmasq
