---
- name: Install NFS server
  ansible.builtin.package:
    name: nfs-kernel-server
    state: present

- name: Restart/Start service nfs server
  ansible.builtin.service:
    name: nfs-kernel-server
    state: started
    enabled: yes

- name: Copy Config /etc/exports
  ansible.builtin.copy:
    src: exports
    dest: /etc/exports
    owner: root
    group: root
    mode: '0644' 
    notify:
      - Export nfs volumes
