---
- name: Install iptables-persistent
  become: true
  ansible.builtin.package:
    name:
      - iptables-persistent
    state: present

- name: Add an Ethernet connection with static IP configuration
  become: true
  community.general.nmcli:
    conn_name: int-eth0
    ifname: eth0
    type: ethernet
    ip4: 192.168.254.1/24
    state: present

- name: Enable ipv4 ip_forwarding in sysctl.conf
  become: true 
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: yes
    sysctl_file: /etc/sysctl.conf

- name: Add the MASQUERADE rule to the POSTROUTING chain
  become: true 
  ansible.builtin.iptables:
    table: nat
    chain: POSTROUTING
    out_interface: 'eth1'
    source: '192.168.254.0/24'
    jump: MASQUERADE
    state: present

- name: Allow related and established connections (essential for return traffic)
  become: true 
  ansible.builtin.iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
    state: present

- name: Save Firewall state
  become: true 
  community.general.iptables_state:
    ip_version: ipv4
    state: saved
    path: /etc/iptables/rules.v4
